name: test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test usage
        run: python -c "from PLS_pytorch import PLS; network = PLS()"
